name: docs

on:
  push:
    branches:
      - main
    tags:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    name:  Documentation check
    env:
      GOBIN: /tmp/.bin
    steps:
      - name: Checkout code into the Go module directory.
        uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          go-version: 1.21.x

      - uses: actions/cache@0c907a75c2c80ebcb7f088228285e798b750cf8f
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

      - name: Check docs
        run: make check-docs
