name: docs

on:
  push:
    branches:
      - main
    tags:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    name:  Documentation check
    env:
      GOBIN: /tmp/.bin
    steps:
      - name: Checkout code into the Go module directory.
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@8e57b58e57be52ac95949151e2777ffda8501267 # v5.0.2
        with:
          go-version: 1.21.x

      - uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

      - name: Check docs
        run: make check-docs
